services:
  - type: web
    name: dream-interpreter
    env: python
    plan: starter

    # Build & start
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"

    # Health check
    healthCheckPath: /healthz

    # Environment
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SHEET_KEY
        value: 1ToWPpJ_u-Z14eqL9U1oJppXX6f63h_eZcjUVglKr4Zk   # <-- your sheet ID
      - key: WORKSHEET_NAME
        value: Sheet1
      - key: ALLOWED_ORIGINS
        value: https://jamaicantruestories.com,https://www.jamaicantruestories.com,https://interpreter.jamaicantruestories.com
      - key: GSPREAD_CREDENTIALS
        value: /etc/secrets/credentials.json