services:
- type: web
name: dream-interpreter
env: python
plan: starter
buildCommand: pip install -r requirements.txt
startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 120
healthCheckPath: /healthz
envVars:
- key: PYTHON_VERSION
value: 3.11.9
- key: WEB_CONCURRENCY
value: 1