<<<<<<< HEAD
services:
- type: web
name: dream-interpreter
env: python
plan: starter
buildCommand: pip install -r requirements.txt
startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120
healthCheckPath: /healthz
envVars:
- key: PYTHON_VERSION
value: 3.11.9
- key: WEB_CONCURRENCY
=======
services:
- type: web
name: dream-interpreter
env: python
plan: starter
buildCommand: pip install -r requirements.txt
startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120
healthCheckPath: /healthz
envVars:
- key: PYTHON_VERSION
value: 3.11.9
- key: WEB_CONCURRENCY
>>>>>>> 51649bdaffc22f088834a7b8700cc617675b2457
value: 1